### ISSUE TITLE
Typo in about.html

### ISSUE THREAD

**Issue by williambelle** [healthonnet/Kconnect-search#139]
**Summary**

Typo in about.html. https://search.kconnect.eu/beta/extension

See https://github.com/healthonnet/Kconnect-search/blob/95f6e7e9c27da1a8ec256437316baef9b8dc4a74/src/views/about.html#L118-L121

**Screenshot**

![selection_013](https://user-images.githubusercontent.com/2843501/34298745-94d5cddc-e71f-11e7-916e-4aec316b34cf.png)

**Comment by williambelle** [comment]
@Pepper-and-mint A little gift for you !

**Comment by Adrion** [comment]
Fixed :)
