### ISSUE TITLE
Ugly missing screenshot

### ISSUE THREAD

**Issue by Adrion** [healthonnet/Kconnect-search#38]
When screenshot service doesn't work we've got an ugly broken img icon in preview.

We have to hide the preview block if image is missing.

**Comment by Adrion** [comment]
We can use something like this directive : http://plnkr.co/edit/to6sADDHJz7QglpsVu1C?p=preview

**Comment by Adrion** [comment]
or use something as a placeholder to handle loading at the same time.
Already used in project : loading-src fallback-src directives in images.html

**Comment by Pierre-RA** [comment]
Fixed with #71.
