### ISSUE TITLE
Filters and sections are sometimes not correct

### ISSUE THREAD

**Issue by Pierre-RA** [healthonnet/Kconnect-search#48]
From Célia:
> quand je selectionne un filtre, le nb de result pour all is false and the display of the other filter is not correct, not all are displayed.

**Comment by Adrion** [comment]
With ne new index we see that sections are ok.
It seems that the issue was a misunderstanding as filters make a `OR` operator and not `AND`.
So with 2 filters have more results than 1 filter. 

Both strategies are ok, but this one is the one used by our legacy controllers
