### ISSUE TITLE
Enable json cors in gulp

### ISSUE THREAD

**Issue by Pierre-RA** [healthonnet/Kconnect-search#5]
http://stackoverflow.com/questions/11001817/allow-cors-rest-request-to-a-express-node-js-application-on-heroku
http://stackoverflow.com/questions/36912610/enable-cors-in-gulp-browsersync

**Comment by Adrion** [comment]
CORS don't have to be enabled browsersync-side, but from the requested server.

I'll check how to make an express proxy to call it from localhost

**Comment by Adrion** [comment]
Fixed in #6
