### ISSUE TITLE
Right side panel has improper behaviour

### ISSUE THREAD

**Issue by Pierre-RA** [healthonnet/Kconnect-search#59]
When browsing results, the right side panel is showing more details about the result. Unfortunately, some users might be confused to which result it belong.

We should probably refactor the code with a better visual aide.
An idea could be a cursor showing the link from left to right.
This visual aide can be found in the boxes from William's HTTP status site:
https://healthonnet.github.io/hon-http-urlchecker/

**Comment by Adrion** [comment]
we can highlight the result with the same color of the right panel. with some paddings it will feel like a clean single block

**Comment by Pierre-RA** [comment]
Also, the right side panel should be fixed.

**Comment by Pierre-RA** [comment]
It should be dealt with the new card system.
